## Imports

In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics.pairwise import cosine_similarity
from sqlalchemy import create_engine
from surprise import SVD, Reader, Dataset
from surprise.model_selection import train_test_split as surprise_train_test_split

## Loading Goodreads Book Graph Datasets

Chose this newer dataset since the Kaggle datasets had outdated books - my target audience is social-media-addicts (young adults), so they won't be interested by old classics. They need to build towards that reading level.

This dataset has an organised collection of books which are popular on goodreads for this age group.

In [2]:
#dataset has 93,398 books
books_ya = pd.read_json("../datasets/goodreads_books_young_adult.json.gz", lines=True)

#dataset has 34,919,254 interactions - interactions read will be truncated to simplify model
interactions = pd.read_json("../datasets/goodreads_interactions_young_adult.json.gz", lines=True, nrows=2000000)

books_ya.to_csv("../datasets/goodreads_books_young_adult.csv", index = False)
interactions.to_csv("../datasets/interactions_young_adult.csv", index = False)

In [3]:
raw_df = interactions.merge(books_ya, on="book_id")

### Cleaning the data

In [4]:
raw_df.columns

Index(['user_id', 'book_id', 'review_id', 'is_read', 'rating',
       'review_text_incomplete', 'date_added', 'date_updated', 'read_at',
       'started_at', 'isbn', 'text_reviews_count', 'series', 'country_code',
       'language_code', 'popular_shelves', 'asin', 'is_ebook',
       'average_rating', 'kindle_asin', 'similar_books', 'description',
       'format', 'link', 'authors', 'publisher', 'num_pages',
       'publication_day', 'isbn13', 'publication_month', 'edition_information',
       'publication_year', 'url', 'image_url', 'ratings_count', 'work_id',
       'title', 'title_without_series'],
      dtype='object')

In [5]:
#removing unnecessary columns

merged_df = raw_df[[
    "user_id",
    "book_id",
    "rating",
    "title",
    "authors",
    "description",
    "publication_year",
    "num_pages",
    "average_rating",
    "ratings_count",
    "image_url",
    "popular_shelves" # to extract the genre
]].copy()

In [6]:
GENRE_SHELVES = {
    "fantasy", "romance", "science-fiction", "sci-fi", "mystery", "thriller",
    "horror", "dystopia", "paranormal", "urban-fantasy", "historical-fiction",
    "contemporary", "adventure", "fiction", "non-fiction", "humor", "comedy",
    "paranormal-romance", "sci-fi-fantasy", "teen-fiction", "young-adult-fiction"
}

def extract_genre(shelves):
    if not isinstance(shelves, list):
        return "unknown"
    for shelf in shelves:
        if shelf["name"] in GENRE_SHELVES:
            return shelf["name"]
    return "unknown"

### Getting the author data

In [7]:
authors_df = pd.read_json( "../datasets/goodreads_book_authors.json.gz", lines=True)

authors_df.to_csv("../datasets/goodreads_book_authors.csv", index = False)

In [8]:
authors_df.columns

Index(['average_rating', 'author_id', 'text_reviews_count', 'name',
       'ratings_count'],
      dtype='object')

### Merging author data with dataset

In [9]:
#loading author data 
authors_df = pd.read_json("../datasets/goodreads_book_authors.json.gz", lines = True)
authors_df.to_csv("../datasets/goodreads_book_authors.csv", index = False)

In [10]:
#converting both to string
authors_df["author_id"] = authors_df["author_id"].astype(str)

In [11]:
#extracting author name
merged_df["author_id"] = merged_df["authors"].apply(
  lambda x: x[0]["author_id"] if isinstance(x, list) and len(x) > 0 else None
)

In [12]:
authored_df = merged_df.merge(authors_df[["author_id","name"]], on="author_id", how="left")

In [13]:
authored_df = authored_df.rename(columns={"name":"author"})

In [14]:
#i only need author names 
authored_df = authored_df.drop(columns=["authors", "author_id"])

In [15]:
authored_df[["title","author"]]

                                              title                 author
0         Popular: Vintage Wisdom for a Modern Geek       Maya Van Wagenen
1         Popular: Vintage Wisdom for a Modern Geek       Maya Van Wagenen
2         Popular: Vintage Wisdom for a Modern Geek       Maya Van Wagenen
3         Popular: Vintage Wisdom for a Modern Geek       Maya Van Wagenen
4         Popular: Vintage Wisdom for a Modern Geek       Maya Van Wagenen
...                                             ...                    ...
1999995                          The Devil You Know           Trish Doller
1999996                                Irresistible             Liz Bankes
1999997  The Lost Kingdom (The Elements Series, #1)         Effie Crescent
1999998                            Peeps (Peeps #1)       Scott Westerfeld
1999999                When the Stars Begin to Fall  James Lincoln Collier

[2000000 rows x 2 columns]

In [16]:
authored_df["genre"] = authored_df["popular_shelves"].apply(extract_genre)
authored_df = authored_df.drop(columns=["popular_shelves"])

print(authored_df["genre"].value_counts())
print(f"\nUnknown: {(authored_df['genre'] == 'unknown').sum()}")

genre
fantasy                675822
romance                270740
contemporary           260686
fiction                219360
dystopia               164279
paranormal             150830
mystery                 63895
science-fiction         51387
sci-fi                  48710
horror                  39102
historical-fiction      19512
humor                   10208
adventure                8589
thriller                 4145
non-fiction              3968
unknown                  3446
young-adult-fiction      2556
paranormal-romance        925
urban-fantasy             887
teen-fiction              411
comedy                    342
sci-fi-fantasy            200
Name: count, dtype: int64

Unknown: 3446

After dropping the columns, all my other cells in this section were no longer needed -- commented out just in case

### Cleaning the data more

In [17]:
# removing non-rated interactions

clean_df = authored_df[authored_df["rating"] > 0].copy()

In [18]:
print("Users:", clean_df["user_id"].nunique())
print("Books:", clean_df["book_id"].nunique())

Users: 24867
Books: 48156

In [19]:
# filtering books with almost no ratings
filtered_df = clean_df.groupby("book_id").filter(lambda x: len(x) >= 5)

In [20]:
filtered_df.shape

(805061, 12)

In [21]:
filtered_df["user_id"].nunique()

24536

In [22]:
filtered_df["book_id"].nunique()

14499

In [23]:
# filtering users who rated fewer than 5 books
filtered_df = filtered_df.groupby("user_id").filter(lambda x: len(x) >= 5) 

#filtered_df.groupby("user_id").size().describe() # how many ratings per users (%)

In [24]:
print("\nFinal dataset:")
print("Shape:", filtered_df.shape)
print("Users:", filtered_df["user_id"].nunique())
print("Books:", filtered_df["book_id"].nunique())
print("\nRatings per user:")
print(filtered_df.groupby("user_id").size().describe())

Final dataset:
Shape: (791225, 12)
Users: 18263
Books: 14494

Ratings per user:
count    18263.000000
mean        43.323934
std         62.616991
min          5.000000
25%         10.000000
50%         22.000000
75%         51.000000
max       1533.000000
dtype: float64

### Building the user-item interaction matrix

In [25]:
interaction_matrix = filtered_df.pivot_table(
    index = "user_id",
    columns = "book_id",
    values = "rating"
)

In [26]:
interaction_matrix.shape

(18263, 14494)

In [27]:
# checking sparsity 

n_users = filtered_df["user_id"].nunique()
n_books = filtered_df["book_id"].nunique()
n_ratings = len(filtered_df)
sparsity = 1 - (n_ratings / (n_users * n_books))
print(f"Sparsity: {sparsity:.4f}")

Sparsity: 0.9970

In [28]:
# checking ratings are between 1-5

print(filtered_df["rating"].value_counts().sort_index())

rating
1     18536
2     53096
3    180196
4    279924
5    259473
Name: count, dtype: int64

In [29]:
interaction_matrix

book_id,50,2811,2913,2915,2917,2931,3304,3402,3467,4043,...,35168764,35180892,35247769,35276925,35451387,35498621,35504431,35521513,35527721,36381037
user_id,,,,,,,,,,,,,,,,,,,,,
0008da70a705b4006dbd5aae83a47cc0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0021909de18ab01ec27517ea8dc0aa93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0021e047a599f9827d75628db22097b6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00254cd48d3d8a99ca9f0ed44fa69d5f,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0028b5eebf06b43b321671ea39e7ca3c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ffe7ed3c8fc20188468ebefdb9f91587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ffe883170a3d48f22a4bacf678c9d2bd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ffec6cbb0db016bc371fc30b902c3166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fff785db3b7a0755573779d6279009de,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
fff917f04fe7bff3a6bf98c541d8324b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Matrix Factorisation using SVD (personalised recommendations based on users with existing ratings)

This is a form of collaborative filtering using matrix factorisation

In [30]:
# define a Reader object to specify the rating scale
reader = Reader(rating_scale = (1,5))

# load into Surprise dataset
data = Dataset.load_from_df(
    filtered_df[["user_id", "book_id", "rating"]],
    reader
)

In [31]:
# splitting the data into train and test sets
trainset, testset = surprise_train_test_split(data, test_size=0.2)

In [32]:
# instantiate the SVD model
svd = SVD()

# train the model on the training set
svd.fit(trainset)

In [33]:
# predict ratings for the test set
predictions = svd.test(testset)

from surprise import accuracy 

# compute and print RMSE (root mean squared error) and MAE (mean absolute error)
rmse = accuracy.rmse(predictions)
mae = accuracy.mae(predictions)

RMSE: 0.8416
MAE:  0.6564

predictions are off by less than one star

In [34]:
from surprise.model_selection import cross_validate

svd_tuned = SVD(n_factors=50, n_epochs=30, lr_all=0.005, reg_all=0.02)
cross_validate(svd_tuned, data, measures=["RMSE", "MAE"], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.8374  0.8415  0.8388  0.8391  0.8425  0.8399  0.0019
MAE (testset)     0.6477  0.6501  0.6480  0.6483  0.6521  0.6492  0.0017
Fit time          11.48   11.83   12.52   13.02   12.40   12.25   0.54
Test time         2.12    2.29    1.90    0.99    1.03    1.67    0.55

{'test_rmse': array([0.83740566, 0.84147823, 0.83879573, 0.83908788, 0.84253374]),
 'test_mae': array([0.64771491, 0.650116  , 0.64798818, 0.64827076, 0.65212665]),
 'fit_time': (11.482839584350586,
  11.830345153808594,
  12.523340940475464,
  13.016064882278442,
  12.399816036224365),
 'test_time': (2.1237680912017822,
  2.2854630947113037,
  1.898726224899292,
  0.9912769794464111,
  1.0288989543914795)}

In [62]:
def get_svd_recommendations(user_id, n=10):
    # get all books this user hasn't rated
    rated_books = filtered_df[filtered_df["user_id"] == user_id]["book_id"].values
    all_books = filtered_df["book_id"].unique()
    unrated_books = [b for b in all_books if b not in rated_books]

    # predict ratings for all unrated books
    predictions_list = [svd.predict(user_id, book_id) for book_id in unrated_books]

    # sort by estimated rating descending
    predictions_list.sort(key=lambda x: x.est, reverse=True)
    top_n = predictions_list[:n]

    # build results dataframe
    book_ids = [p.iid for p in top_n]
    scores = [round(p.est, 3) for p in top_n]

    book_info = filtered_df[["book_id", "title", "author", "genre", "description", "image_url"]].drop_duplicates("book_id")
    results = pd.DataFrame({"book_id": book_ids, "predicted_rating": scores})
    results = results.merge(book_info, on="book_id", how="left")

    return results

In [63]:
sample_user = filtered_df["user_id"].iloc[0]
print(f"Recommendations for user: {sample_user}\n")
print(get_svd_recommendations(sample_user))

Recommendations for user: 0226259f03e2d21ccf7e5752fb386f6b

    book_id  predicted_rating  \
0  12885649             4.917
1  32075671             4.898
2  15746527             4.894
3  27840861             4.884
4    153780             4.878
5  23302416             4.876
6  22552026             4.855
7  10165727             4.843
8  25657130             4.838
9  28145767             4.814

                                             title            author  \
0          The Hunger Games (The Hunger Games, #1)   Suzanne Collins
1                                  The Hate U Give      Angie Thomas
2    Clockwork Princess (The Infernal Devices, #3)   Cassandra Clare
3               Crooked Kingdom (Six of Crows, #2)     Leigh Bardugo
4  Trickster's Queen (Daughter of the Lioness, #2)     Tamora Pierce
5                                           Wonder      R.J. Palacio
6                                    Long Way Down    Jason Reynolds
7     Froi of the Exiles (Lumatere Chronicles, #2)  Melina Marchetta
8                                All American Boys    Jason Reynolds
9    Strange the Dreamer (Strange the Dreamer, #1)      Laini Taylor

          genre                                        description  \
0       fiction  Winning will make you famous.\nLosing means ce...
1  contemporary  Sixteen-year-old Starr Carter moves between tw...
2       fantasy  If the only way to save the world was to destr...
3       fantasy  When you can't beat the odds, change the game....
4       fantasy  The stage is set for revolution...\nAly:no lon...
5       fiction  You can't blend in when you were born to stand...
6  contemporary  A cannon. A strap.\nA piece. A biscuit.\nA bur...
7       fantasy  Blood sings to blood, Froi . . .\nThose born l...
8  contemporary  Rashad is absent again today.\nThat's the side...
9       fantasy  Strange the Dreameris the story of:\nthe after...

                                           image_url
0  https://images.gr-assets.com/books/1327089453m...
1  https://images.gr-assets.com/books/1476284759m...
2  https://images.gr-assets.com/books/1345320357m...
3  https://images.gr-assets.com/books/1456172649m...
4  https://s.gr-assets.com/assets/nophoto/book/11...
5  https://images.gr-assets.com/books/1412358842m...
6  https://images.gr-assets.com/books/1508974864m...
7  https://images.gr-assets.com/books/1306866851m...
8  https://images.gr-assets.com/books/1444506678m...
9  https://images.gr-assets.com/books/1459437419m...

### Popularity-based recommender model

In [37]:
#ratings_with_name = ratings.merge(books, on='ISBN')

In [38]:
#count ratings per book

num_rating_df = filtered_df.groupby("book_id")["rating"].count().reset_index()
num_rating_df.rename(columns= {"rating":"num_ratings"}, inplace = True)
num_rating_df

        book_id  num_ratings
0            50          925
1          2811           43
2          2913           29
3          2915           77
4          2917           13
...         ...          ...
14489  35498621            6
14490  35504431          119
14491  35521513            6
14492  35527721           10
14493  36381037            6

[14494 rows x 2 columns]

In [39]:
# finding the average rating for each book

avg_rating_df = filtered_df.groupby("book_id")["rating"].mean().reset_index()
avg_rating_df.rename(columns= {"rating": "avg_rating"}, inplace = True)
avg_rating_df

        book_id  avg_rating
0            50    3.564324
1          2811    3.767442
2          2913    3.655172
3          2915    3.558442
4          2917    4.000000
...         ...         ...
14489  35498621    4.500000
14490  35504431    4.226891
14491  35521513    4.333333
14492  35527721    4.100000
14493  36381037    4.000000

[14494 rows x 2 columns]

In [40]:
# merging the two tables to create a new popular books dataframe

book_info = filtered_df[["book_id", "title", "author","genre", "description","image_url"]].drop_duplicates("book_id")
popular_df = num_rating_df.merge(avg_rating_df, on = "book_id").merge(book_info, on="book_id")
popular_df

,book_id,num_ratings,avg_rating,title,author,genre,description,image_url
0,50,925,3.564324,"Hatchet (Brian's Saga, #1)",Gary Paulsen,fiction,Brian is on his way to Canada to visit his est...,https://s.gr-assets.com/assets/nophoto/book/11...
1,2811,43,3.767442,"A House Like a Lotus (O'Keefe Family, #3)",Madeleine L'Engle,fiction,When sixteen-year-old Polly O'Keefe journeys t...,https://images.gr-assets.com/books/1432668936m...
2,2913,29,3.655172,"Brian's Hunt (Brian's Saga, #5)",Gary Paulsen,fiction,"Millions of readers of"" Hatchet, The River, Br...",https://s.gr-assets.com/assets/nophoto/book/11...
3,2915,77,3.558442,"The River (Brian's Saga, #2)",Gary Paulsen,fiction,"""We want you to do it again.""\nThese words, sp...",https://s.gr-assets.com/assets/nophoto/book/11...
4,2917,13,4.000000,How Angel Peterson Got His Name,Gary Paulsen,humor,When you grow up in a small town in the north ...,https://s.gr-assets.com/assets/nophoto/book/11...
...,...,...,...,...,...,...,...,...
14489,35498621,6,4.500000,Turtles All the Way Down,John Green,contemporary,#1 bestselling author John Green returns with ...,https://images.gr-assets.com/books/1502482900m...
14490,35504431,119,4.226891,Turtles All the Way Down,John Green,contemporary,Sixteen-year-old Aza never intended to pursue ...,https://images.gr-assets.com/books/1503002776m...
14491,35521513,6,4.333333,Turtles All the Way Down,John Green,contemporary,It all begins with a fugitive billionaire and ...,https://images.gr-assets.com/books/1502483006m...
14492,35527721,10,4.100000,The Hate U Give,Angie Thomas,contemporary,"Inspired by the Black Lives Matter movement, A...",https://images.gr-assets.com/books/1500008032m...
14493,36381037,6,4.000000,"Cinder (The Lunar Chronicles, #1)",Marissa Meyer,fantasy,Humans and androids crowd the raucous streets ...,https://images.gr-assets.com/books/1507557775m...

In [41]:
# measuring the Bayesian average score -- this means books with a higher volume of ratings are prioritised 
# over smaller volume of ratings but high ratings

C = popular_df["num_ratings"].mean() # average number of ratings across all books
m = popular_df["avg_rating"].mean() # global mean rating

popular_df["score"] = ((popular_df["num_ratings"] * popular_df["avg_rating"]) + (C*m)) / (popular_df["num_ratings"] + C)

In [42]:
# filter to books with a minimum number of ratings then rank

MIN_RATINGS = 50

popular_df = popular_df[popular_df["num_ratings"] >= MIN_RATINGS]
popular_df = popular_df.sort_values("score", ascending = False).reset_index(drop=True)
popular_df

,book_id,num_ratings,avg_rating,title,author,genre,description,image_url,score
0,32075671,553,4.634720,The Hate U Give,Angie Thomas,contemporary,Sixteen-year-old Starr Carter moves between tw...,https://images.gr-assets.com/books/1476284759m...,4.557379
1,17340050,673,4.576523,"Losing Hope (Hopeless, #2)",Colleen Hoover,romance,In the follow-up to Colleen Hoover's #1 New Yo...,https://images.gr-assets.com/books/1368348507m...,4.516305
2,6131164,859,4.563446,"Clockwork Princess (The Infernal Devices, #3)",Cassandra Clare,fantasy,"Danger and betrayal, secrets and enchantment i...",https://images.gr-assets.com/books/1460477760m...,4.516269
3,18006496,734,4.550409,"Queen of Shadows (Throne of Glass, #4)",Sarah J. Maas,fantasy,The queen has returned.\nEveryone Celaena Sard...,https://images.gr-assets.com/books/1441230104m...,4.496656
4,11387515,1149,4.512620,Wonder (Wonder #1),R.J. Palacio,fiction,I won't describe what I look like. Whatever yo...,https://images.gr-assets.com/books/1309285027m...,4.479115
...,...,...,...,...,...,...,...,...,...
2363,8517207,129,3.054264,"Bumped (Bumped, #1)",Megan McCafferty,dystopia,When a virus makes everyone over the age of ei...,https://images.gr-assets.com/books/1288711015m...,3.268249
2364,6638377,91,2.956044,Nightlight: A Parody,The Harvard Lampoon,humor,About three things I was absolutely certain.\n...,https://images.gr-assets.com/books/1320519788m...,3.262710
2365,26860475,137,3.021898,"Twilight / Life and Death (Twilight, #1, 1.75)",Stephenie Meyer,fantasy,Celebrate the tenth anniversary of Twilight! T...,https://images.gr-assets.com/books/1506725125m...,3.236170
2366,2508164,103,2.883495,"Ghostgirl (Ghostgirl, #1)",Tonya Hurley,paranormal,"Now I lay me down to sleep,\nI pray the Lord m...",https://s.gr-assets.com/assets/nophoto/book/11...,3.191940
2367,8913852,92,2.510870,Sweet Valley Confidential: Ten Years Later,Francine Pascal,fiction,Ten years after graduating from Sweet Valley H...,https://s.gr-assets.com/assets/nophoto/book/11...,2.981226

In [43]:
popular_df_no_duplicates = (popular_df
    .sort_values("num_ratings", ascending=False)
    .drop_duplicates(subset="title", keep="first")
    .sort_values("score", ascending=False)
    .reset_index(drop=True)
)

In [44]:
print(f"Books before dedup: {len(popular_df) + 134}")
print(f"Books after dedup: {len(popular_df_no_duplicates)}")
print(popular_df_no_duplicates.head(10)[["title", "author", "num_ratings", "avg_rating", "score"]])

Books before dedup: 2502
Books after dedup: 2234
                                               title                  author  \
0                                    The Hate U Give            Angie Thomas
1                         Losing Hope (Hopeless, #2)          Colleen Hoover
2      Clockwork Princess (The Infernal Devices, #3)         Cassandra Clare
3             Queen of Shadows (Throne of Glass, #4)           Sarah J. Maas
4                                 Wonder (Wonder #1)            R.J. Palacio
5  The Hunger Games Trilogy Boxset (The Hunger Ga...         Suzanne Collins
6                            Hopeless (Hopeless, #1)          Colleen Hoover
7                 Crooked Kingdom (Six of Crows, #2)           Leigh Bardugo
8            The Hunger Games (The Hunger Games, #1)         Suzanne Collins
9                               Deity (Covenant, #3)  Jennifer L. Armentrout

   num_ratings  avg_rating     score
0          553    4.634720  4.557379
1          673    4.576523  4.516305
2          859    4.563446  4.516269
3          734    4.550409  4.496656
4         1149    4.512620  4.479115
5          593    4.539629  4.475082
6         1620    4.495679  4.472150
7          427    4.550351  4.462340
8        12091    4.446200  4.443178
9          392    4.530612  4.438116

In [45]:
popular_df_no_duplicates

,book_id,num_ratings,avg_rating,title,author,genre,description,image_url,score
0,32075671,553,4.634720,The Hate U Give,Angie Thomas,contemporary,Sixteen-year-old Starr Carter moves between tw...,https://images.gr-assets.com/books/1476284759m...,4.557379
1,17340050,673,4.576523,"Losing Hope (Hopeless, #2)",Colleen Hoover,romance,In the follow-up to Colleen Hoover's #1 New Yo...,https://images.gr-assets.com/books/1368348507m...,4.516305
2,6131164,859,4.563446,"Clockwork Princess (The Infernal Devices, #3)",Cassandra Clare,fantasy,"Danger and betrayal, secrets and enchantment i...",https://images.gr-assets.com/books/1460477760m...,4.516269
3,18006496,734,4.550409,"Queen of Shadows (Throne of Glass, #4)",Sarah J. Maas,fantasy,The queen has returned.\nEveryone Celaena Sard...,https://images.gr-assets.com/books/1441230104m...,4.496656
4,11387515,1149,4.512620,Wonder (Wonder #1),R.J. Palacio,fiction,I won't describe what I look like. Whatever yo...,https://images.gr-assets.com/books/1309285027m...,4.479115
...,...,...,...,...,...,...,...,...,...
2229,8517207,129,3.054264,"Bumped (Bumped, #1)",Megan McCafferty,dystopia,When a virus makes everyone over the age of ei...,https://images.gr-assets.com/books/1288711015m...,3.268249
2230,6638377,91,2.956044,Nightlight: A Parody,The Harvard Lampoon,humor,About three things I was absolutely certain.\n...,https://images.gr-assets.com/books/1320519788m...,3.262710
2231,26860475,137,3.021898,"Twilight / Life and Death (Twilight, #1, 1.75)",Stephenie Meyer,fantasy,Celebrate the tenth anniversary of Twilight! T...,https://images.gr-assets.com/books/1506725125m...,3.236170
2232,2508164,103,2.883495,"Ghostgirl (Ghostgirl, #1)",Tonya Hurley,paranormal,"Now I lay me down to sleep,\nI pray the Lord m...",https://s.gr-assets.com/assets/nophoto/book/11...,3.191940
2233,8913852,92,2.510870,Sweet Valley Confidential: Ten Years Later,Francine Pascal,fiction,Ten years after graduating from Sweet Valley H...,https://s.gr-assets.com/assets/nophoto/book/11...,2.981226

In [99]:
# to get the image of the book 
popular_df_no_duplicates["image_url"][4]

'https://images.gr-assets.com/books/1309285027m/11387515.jpg'

### Recommendation pipline

To address the cold-start problem, if users have rated less than 5 books, users are recommended books based on their popularity according to other users of the same demographic. Since my target audience is young adults, all recommended books are YA and are highly rated (using Bayesian average).

If the user already rated previous books, they will get personalised recomemndations based on a rating prediction on new unread books.

In [46]:
def get_recommendations(user_id, n=10):
    user_ratings = filtered_df[filtered_df["user_id"] == user_id]
    
    if len(user_ratings) < 5:
        # Cold start — return popular books
        return popular_df.head(n)
    else:
        # Enough interactions — use SVD
        return get_svd_recommendations(user_id, n)

In [61]:
### Unified Recommendation Pipeline

from sqlalchemy import text

def get_recommendations(user_id, n=10):
    """
    Returns top-n book recommendations for a user.
    - Cold start (< 5 ratings): falls back to popularity-based recommendations.
    - Warm start (>= 5 ratings): uses SVD collaborative filtering.
    """
    user_ratings = filtered_df[filtered_df["user_id"] == user_id]

    if len(user_ratings) < 5:
        # Cold start — return top popular books the user hasn't rated
        rated_ids = set(user_ratings["book_id"].values)
        recs = (
            popular_df_no_duplicates[~popular_df_no_duplicates["book_id"].isin(rated_ids)]
            .head(n)[["book_id", "title", "author", "genre", "description", "image_url", "score"]]
            .rename(columns={"score": "predicted_rating"})
            .copy()
        )
        recs["method"] = "popularity"
    else:
        # Warm start — SVD
        recs = get_svd_recommendations(user_id, n)
        recs["method"] = "svd"

    recs["user_id"] = user_id
    return recs

In [57]:
sample_user = filtered_df["user_id"].iloc[0]

# test cold start (user with < 5 ratings)
print("COLD START:")
print(get_recommendations("cold_user"))

# test warm start (user with >= 5 ratings)
warm_user = filtered_df.groupby("user_id").filter(lambda x: len(x) >= 5)["user_id"].iloc[0]
print("\nWARM START (SVD):")
print(get_recommendations(warm_user))

COLD START:
    book_id                                              title  \
0  32075671                                    The Hate U Give
1  17340050                         Losing Hope (Hopeless, #2)
2   6131164      Clockwork Princess (The Infernal Devices, #3)
3  18006496             Queen of Shadows (Throne of Glass, #4)
4  11387515                                 Wonder (Wonder #1)
5   7938275  The Hunger Games Trilogy Boxset (The Hunger Ga...
6  15717943                            Hopeless (Hopeless, #1)
7  22299763                 Crooked Kingdom (Six of Crows, #2)
8   2767052            The Hunger Games (The Hunger Games, #1)
9   9761778                               Deity (Covenant, #3)

                   author         genre  \
0            Angie Thomas  contemporary
1          Colleen Hoover       romance
2         Cassandra Clare       fantasy
3           Sarah J. Maas       fantasy
4            R.J. Palacio       fiction
5         Suzanne Collins       fiction
6          Colleen Hoover       romance
7           Leigh Bardugo       fantasy
8         Suzanne Collins       fiction
9  Jennifer L. Armentrout       fantasy

                                         description  predicted_rating  \
0  Sixteen-year-old Starr Carter moves between tw...          4.557379
1  In the follow-up to Colleen Hoover's #1 New Yo...          4.516305
2  Danger and betrayal, secrets and enchantment i...          4.516269
3  The queen has returned.\nEveryone Celaena Sard...          4.496656
4  I won't describe what I look like. Whatever yo...          4.479115
5  The extraordinary, ground breaking New York Ti...          4.475082
6  Sometimes discovering the truth can leave you ...          4.472150
7  Welcome to the world of the Grisha.\nAfter pul...          4.462340
8  Winning will make you famous.\nLosing means ce...          4.443178
9  History is on repeat, and things didn't go so ...          4.438116

       method    user_id
0  popularity  cold_user
1  popularity  cold_user
2  popularity  cold_user
3  popularity  cold_user
4  popularity  cold_user
5  popularity  cold_user
6  popularity  cold_user
7  popularity  cold_user
8  popularity  cold_user
9  popularity  cold_user

WARM START (SVD):
    book_id  predicted_rating  \
0  12885649             4.917
1  32075671             4.898
2  15746527             4.894
3  27840861             4.884
4    153780             4.878
5  23302416             4.876
6  22552026             4.855
7  10165727             4.843
8  25657130             4.838
9  28145767             4.814

                                             title            author  \
0          The Hunger Games (The Hunger Games, #1)   Suzanne Collins
1                                  The Hate U Give      Angie Thomas
2    Clockwork Princess (The Infernal Devices, #3)   Cassandra Clare
3               Crooked Kingdom (Six of Crows, #2)     Leigh Bardugo
4  Trickster's Queen (Daughter of the Lioness, #2)     Tamora Pierce
5                                           Wonder      R.J. Palacio
6                                    Long Way Down    Jason Reynolds
7     Froi of the Exiles (Lumatere Chronicles, #2)  Melina Marchetta
8                                All American Boys    Jason Reynolds
9    Strange the Dreamer (Strange the Dreamer, #1)      Laini Taylor

          genre                                        description method  \
0       fiction  Winning will make you famous.\nLosing means ce...    svd
1  contemporary  Sixteen-year-old Starr Carter moves between tw...    svd
2       fantasy  If the only way to save the world was to destr...    svd
3       fantasy  When you can't beat the odds, change the game....    svd
4       fantasy  The stage is set for revolution...\nAly:no lon...    svd
5       fiction  You can't blend in when you were born to stand...    svd
6  contemporary  A cannon. A strap.\nA piece. A biscuit.\nA bur...    svd
7       fantasy  Blood sings to blood, Froi . . .\nThose born l...    svd
8  contemporary  Rashad is absent again today.\nThat's the side...    svd
9       fantasy  Strange the Dreameris the story of:\nthe after...    svd

                            user_id
0  0226259f03e2d21ccf7e5752fb386f6b
1  0226259f03e2d21ccf7e5752fb386f6b
2  0226259f03e2d21ccf7e5752fb386f6b
3  0226259f03e2d21ccf7e5752fb386f6b
4  0226259f03e2d21ccf7e5752fb386f6b
5  0226259f03e2d21ccf7e5752fb386f6b
6  0226259f03e2d21ccf7e5752fb386f6b
7  0226259f03e2d21ccf7e5752fb386f6b
8  0226259f03e2d21ccf7e5752fb386f6b
9  0226259f03e2d21ccf7e5752fb386f6b

In [ ]:
def push_recommendations_to_db_2(user_id, engine, n=10):
    """
    Generates recommendations for a user and writes them to the
    'recommendations' table, replacing all existing rows for that user.
    """
    recs = get_recommendations(user_id, n)

    if recs.empty:
        print(f"No recommendations generated for user {user_id}.")
        return

    to_save = recs[["user_id", "book_id", "predicted_rating"]].rename(
        columns={"predicted_rating": "score"}
    )

    with engine.begin() as conn:
        conn.execute(
            text("DELETE FROM recommendations WHERE user_id = :uid"),
            {"uid": user_id}
        )
        to_save.to_sql("recommendations", conn, if_exists="append", index=False)

    print(f"✓ Pushed {len(to_save)} recommendations for user {user_id} "
          f"(method: {recs['method'].iloc[0]})")
    return to_save

In [ ]:
#push_recommendations_to_db(sample_user, engine, n=10)

In [67]:
def push_recommendations_to_db(user_id, engine, n=10):
    recs = get_recommendations(user_id, n)

    if recs.empty:
        print(f"No recommendations generated for user {user_id}.")
        return

    # --- 1. Upsert books into the book table ---
    #books_to_save = recs[["book_id", "title", "author", "description", "genre", "image_url"]].copy()
    books_to_save = recs.reset_index(drop=True)[["book_id", "title", "author", "description", "genre", "image_url"]].copy()
    books_to_save = books_to_save.rename(columns={
        "book_id": "external_id",
        "image_url": "cover_url"
    })
    books_to_save["source"] = "goodreads"

    with engine.begin() as conn:
        for _, row in books_to_save.iterrows():
            conn.execute(text("""
                INSERT INTO book (external_id, title, author, description, genre, cover_url, source)
                VALUES (:external_id, :title, :author, :description, :genre, :cover_url, :source)
                ON CONFLICT (external_id) DO UPDATE SET
                    title = EXCLUDED.title,
                    author = EXCLUDED.author,
                    description = EXCLUDED.description,
                    genre = EXCLUDED.genre,
                    cover_url = EXCLUDED.cover_url,
                    source = EXCLUDED.source
            """), row.to_dict())

        # --- 2. Fetch the internal book IDs just inserted/updated ---
        external_ids = recs["book_id"].astype(str).tolist()
        result = conn.execute(text("""
            SELECT id, external_id FROM book
            WHERE external_id = ANY(:ids)
        """), {"ids": external_ids})
        id_map = {str(row.external_id): row.id for row in result}

        # --- 3. Replace recommendations for this user ---
        conn.execute(text("DELETE FROM recommendations WHERE user_id = :uid"), {"uid": user_id})

        recs_to_save = pd.DataFrame({
            "user_id": user_id,
            "book_id": [id_map[str(bid)] for bid in recs["book_id"]],
            "score": recs["predicted_rating"].values
        })
        recs_to_save.to_sql("recommendations", conn, if_exists="append", index=False)

    print(f"✓ Saved {len(books_to_save)} books and {len(recs_to_save)} recommendations for user {user_id}")
    return recs_to_save

In [69]:
push_recommendations_to_db(user_id=1, engine=engine, n=10)

✓ Saved 10 books and 10 recommendations for user 1

   user_id  book_id     score
0        1     4715  4.557379
1        1     4716  4.516305
2        1     4717  4.516269
3        1     4718  4.496656
4        1     4719  4.479115
5        1     4720  4.475082
6        1     4721  4.472150
7        1     4722  4.462340
8        1     4723  4.443178
9        1     4724  4.438116

In [66]:
recs = get_recommendations(sample_user)
print(recs.columns.tolist())

['book_id', 'predicted_rating', 'title', 'author', 'genre', 'description', 'image_url', 'method', 'user_id']

### Collaborative filtering based recommender model

In [12]:
# getting users who have rated 20 or more books

x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] >= 20
educated_users = x[x].index

In [13]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(educated_users)]

In [14]:
# getting the popular books based on users with 20 or more ratings

y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 20
popular_by_educated_users = y[y].index

In [15]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(popular_by_educated_users)]

In [16]:
pt = final_ratings.pivot_table(index = 'Book-Title', columns='User-ID', values='Book-Rating')

In [17]:
pt.fillna(0,inplace=True) # replacing NaN with 0
pt

User-ID,4017,6242,6251,6563,6575,7346,8245,8253,8454,10314,...,261829,264031,264543,265115,266056,268110,270605,270713,271448,274301
Book-Title,,,,,,,,,,,,,,,,,,,,,
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Map of the World,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0
A Painted House,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0
A Prayer for Owen Meany,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
We Were the Mulvaneys,10.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0
What Looks Like Crazy On An Ordinary Day,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,6.0,0.0,10.0,7.0,0.0
Where the Heart Is (Oprah's Book Club (Paperback)),0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,10.0,5.0,10.0,0.0
White Oleander : A Novel,0.0,0.0,8.0,0.0,0.0,0.0,0.0,10.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0
Wicked: The Life and Times of the Wicked Witch of the West,0.0,7.0,0.0,8.0,9.0,7.0,0.0,0.0,10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
#computing similarity between each pair of books 

similarity_scores = cosine_similarity(pt)
similarity_scores.shape

(79, 79)

In [56]:
#making recommendations based on a book read -- can be used for "because you read x..."

def recommend(book_name):
    # index fetch 
    index = np.where(pt.index == book_name)[0][0]
    # fetching 25 similar books (to be used in a row)
    similar_items = sorted(list(enumerate(similarity_scores[index])), key=lambda x:x[1], reverse=True)[1:25]

    data = []
    for i in similar_items:
        item = []
        
        temp_df = books[books['Book-Title']==pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))

        data.append(item)

    return data

In [57]:
recommend('Wicked: The Life and Times of the Wicked Witch of the West')

[['Me Talk Pretty One Day',
  'David Sedaris',
  'http://images.amazon.com/images/P/0316776963.01.MZZZZZZZ.jpg'],
 ['The Nanny Diaries: A Novel',
  'Emma McLaughlin',
  'http://images.amazon.com/images/P/0312278586.01.MZZZZZZZ.jpg'],
 ['Harry Potter and the Goblet of Fire (Book 4)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439139597.01.MZZZZZZZ.jpg'],
 ['Empire Falls',
  'Richard Russo',
  'http://images.amazon.com/images/P/0375726403.01.MZZZZZZZ.jpg'],
 ['Girl in Hyacinth Blue',
  'Susan Vreeland',
  'http://images.amazon.com/images/P/014029628X.01.MZZZZZZZ.jpg'],
 ["Bridget Jones's Diary",
  'Helen Fielding',
  'http://images.amazon.com/images/P/0330332775.01.MZZZZZZZ.jpg'],
 ['A Map of the World',
  'Jane Hamilton',
  'http://images.amazon.com/images/P/0385720106.01.MZZZZZZZ.jpg'],
 ['The Secret Life of Bees',
  'Sue Monk Kidd',
  'http://images.amazon.com/images/P/0142001740.01.MZZZZZZZ.jpg'],
 ["The Sweet Potato Queens' Book of Love",
  'JILL CONNER BROWNE',
  'http://images.amazon.com/images/P/0609804138.01.MZZZZZZZ.jpg'],
 ['White Oleander : A Novel',
  'Janet Fitch',
  'http://images.amazon.com/images/P/0316182540.01.MZZZZZZZ.jpg'],
 ['Midwives: A Novel',
  'Chris Bohjalian',
  'http://images.amazon.com/images/P/0375706771.01.MZZZZZZZ.jpg'],
 ["The Girls' Guide to Hunting and Fishing",
  'Melissa Bank',
  'http://images.amazon.com/images/P/0140293248.01.MZZZZZZZ.jpg'],
 ['Good in Bed',
  'Jennifer Weiner',
  'http://images.amazon.com/images/P/0743418174.01.MZZZZZZZ.jpg'],
 ['A Painted House',
  'John Grisham',
  'http://images.amazon.com/images/P/044023722X.01.MZZZZZZZ.jpg'],
 ['STONES FROM THE RIVER',
  'Ursula Hegi',
  'http://images.amazon.com/images/P/068484477X.01.MZZZZZZZ.jpg'],
 ['A Prayer for Owen Meany',
  'John Irving',
  'http://images.amazon.com/images/P/0345361792.01.MZZZZZZZ.jpg'],
 ['Harry Potter and the Chamber of Secrets (Book 2)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439064872.01.MZZZZZZZ.jpg'],
 ['House of Sand and Fog',
  'Andre Dubus III',
  'http://images.amazon.com/images/P/0375727345.01.MZZZZZZZ.jpg'],
 ['Two for the Dough',
  'Janet Evanovich',
  'http://images.amazon.com/images/P/0671001795.01.MZZZZZZZ.jpg'],
 ['The Red Tent (Bestselling Backlist)',
  'Anita Diamant',
  'http://images.amazon.com/images/P/0312195516.01.MZZZZZZZ.jpg'],
 ['Four To Score (A Stephanie Plum Novel)',
  'Janet Evanovich',
  'http://images.amazon.com/images/P/0312966970.01.MZZZZZZZ.jpg'],
 ['What Looks Like Crazy On An Ordinary Day',
  'Pearl Cleage',
  'http://images.amazon.com/images/P/038079487X.01.MZZZZZZZ.jpg'],
 ['Harry Potter and the Prisoner of Azkaban (Book 3)',
  'J. K. Rowling',
  'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'],
 ["Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson",
  'MITCH ALBOM',
  'http://images.amazon.com/images/P/0385484518.01.MZZZZZZZ.jpg']]

In [58]:
#import pickle
#pickle.dump(popular_df, open('popular.pkl','wb'))

#pickle.dump(pt,open('pt.pkl','wb'))
#pickle.dump(pt,open('books.pkl','wb'))
#pickle.dump(pt,open('similarity_scores.pkl','wb'))

### Database connection

In [47]:
connection_string = "postgresql://postgres:Dormezzled79!@35.246.42.56:5432/postgres"
engine = create_engine(connection_string)

# testing connection
try:
    with engine.connect() as conn:
        print("✓ Connected to database successfully!")
except Exception as e:
    print(f"✗ Connection failed: {e}")

✓ Connected to database successfully!

### Loading data

In [28]:
books_df = pd.read_sql("SELECT * FROM book", engine) 
library_df = pd.read_sql("SELECT * FROM use_library", engine)

### Getting all user-book interactions

In [29]:
# books in user's library
positive_examples = library_df.copy()
positive_examples['liked'] = 1

# books NOT in user's library (random sample)
user_books = set(library_df['book_id'].values)
all_books = set(books_df['id'].values)
not_liked_books = list(all_books - user_books)

# sample negative examples (2x the positive examples for balance)
random.seed(42)
negative_samples = random.sample(not_liked_books, min(len(positive_examples) * 2, len(not_liked_books)))

negative_examples = pd.DataFrame({
    'user_id': [1] * len(negative_samples),
    'book_id': negative_samples,
    'liked': [0] * len(negative_samples)
})

### Generating training data

In [30]:
# combining positive and negative examples
training_data = pd.concat([positive_examples, negative_examples], ignore_index=True)

# merging with book features (genre and author)
training_with_features = training_data.merge(
    books_df[['id', 'genre', 'author']], 
    left_on='book_id', 
    right_on='id'
)

In [31]:
print(f"Training samples: {len(training_with_features)}")
print(f"Positive (liked): {sum(training_with_features['liked'] == 1)}")
print(f"Negative (not liked): {sum(training_with_features['liked'] == 0)}")
print("\nSample training data:")
print(training_with_features.head())

Training samples: 30
Positive (liked): 10
Negative (not liked): 20

Sample training data:
   user_id  book_id  liked    id                    genre          author
0        1     4663      1  4663  Psychological Thrillers    Celina Grace
1        1     4564      1  4564  Psychological Thrillers     Molly Black
2        1     4636      1  4636           Modern Romance    Jule McBride
3        1     4585      1  4585       BookTok Favourites  Trevor Boffone
4        1     4568      1  4568  Psychological Thrillers      Ella Swift

### Encoding features and training model

In [32]:
genre_encoder = LabelEncoder()
author_encoder = LabelEncoder()

# fitting and transform the features
training_with_features['genre_encoded'] = genre_encoder.fit_transform(training_with_features['genre'])
training_with_features['author_encoded'] = author_encoder.fit_transform(training_with_features['author'])

X = training_with_features[['genre_encoded', 'author_encoded']]
y = training_with_features['liked']

# splitting into train and test sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Training set: {len(X_train)} samples")
print(f"Test set: {len(X_test)} samples")

Training set: 24 samples
Test set: 6 samples

In [33]:
# training the model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# predictions on the test set
y_pred = model.predict(X_test)

# evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2%}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Not Liked', 'Liked']))

feature_importance = pd.DataFrame({
    'Feature': ['Genre', 'Author'],
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)

print("\nFeature Importance:")
print(feature_importance)

Model Accuracy: 66.67%

Classification Report:
              precision    recall  f1-score   support

   Not Liked       0.75      0.75      0.75         4
       Liked       0.50      0.50      0.50         2

    accuracy                           0.67         6
   macro avg       0.62      0.62      0.62         6
weighted avg       0.67      0.67      0.67         6


Feature Importance:
  Feature  Importance
1  Author    0.824004
0   Genre    0.175996

### Generating recommendations

In [34]:
# Prepare all books for prediction (exclude books already in library)
books_to_recommend = books_df[~books_df['id'].isin(library_df['book_id'])].copy()

# Only keep books with genres/authors the model has seen during training
known_genres = set(genre_encoder.classes_)
known_authors = set(author_encoder.classes_)

books_to_recommend = books_to_recommend[
    (books_to_recommend['genre'].isin(known_genres)) & 
    (books_to_recommend['author'].isin(known_authors))
].copy()

print(f"Books that can be scored: {len(books_to_recommend)} out of {len(books_df) - len(library_df)}")

books_to_recommend['genre_encoded'] = genre_encoder.transform(books_to_recommend['genre'])
books_to_recommend['author_encoded'] = author_encoder.transform(books_to_recommend['author'])

X_recommend = books_to_recommend[['genre_encoded', 'author_encoded']]
books_to_recommend['prediction'] = model.predict(X_recommend)
books_to_recommend['prediction_proba'] = model.predict_proba(X_recommend)[:, 1]

# top 10 recommendations
top_recommendations = books_to_recommend[books_to_recommend['prediction'] == 1].sort_values(
    'prediction_proba', ascending=False
).head(10)

print(f"\nTotal books predicted as 'Liked': {sum(books_to_recommend['prediction'] == 1)}")
print("\nTop 10 Recommendations:")
print(top_recommendations[['title', 'author', 'genre', 'prediction_proba']])

Books that can be scored: 51 out of 167

Total books predicted as 'Liked': 5

Top 10 Recommendations:
                                                 title          author  \
20   Secret Baby Spencer (Mills & Boon American Rom...    Jule McBride
77                                  Prescription: Baby    Jule McBride
65                   The Complete Christmas Collection  Cathy Williams
122  Hidden Desire: Enthralled by Moretti / A Game ...  Cathy Williams
13                                   My Favorite Witch   Annette Blair

              genre  prediction_proba
20   Modern Romance              0.67
77   Modern Romance              0.67
65   Modern Romance              0.64
122  Modern Romance              0.64
13   Modern Romance              0.60

### Saving the recommendations to the database

In [35]:
recommendations_to_save = top_recommendations[['id']].copy()
recommendations_to_save['user_id'] = 1
recommendations_to_save['book_id'] = recommendations_to_save['id']
recommendations_to_save['score'] = top_recommendations['prediction_proba'].values
recommendations_to_save = recommendations_to_save[['user_id', 'book_id', 'score']]

print("Recommendations to save:")
print(recommendations_to_save)

recommendations_to_save.to_sql(
    'recommendations', 
    engine, 
    if_exists='replace',  
    index=False
)

print("\n✓ Recommendations saved to 'recommendations' table!")

Recommendations to save:
     user_id  book_id  score
20         1     4639   0.67
77         1     4647   0.67
65         1     4644   0.64
122        1     4635   0.64
13         1     4573   0.60

✓ Recommendations saved to 'recommendations' table!